### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by vpolinov** [kevin-doolaeghe/rtl88x2bu_wifi_driver#1]
root@LMINT:/home/me/Downloads/rtl88x2bu# iwconfig
lo        no wireless extensions.

eno1      no wireless extensions.

wlxd03745a39c86  unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.412 GHz  Access Point: Not-Associated   
          Sensitivity:0/0  
          Retry:off   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          Link Quality=0/100  Signal level=0 dBm  Noise level=0 dBm
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

**Comment by kevin-doolaeghe** [comment]
Is wlxd03745a39c86 your integrated wlan interface ?
The commands wrote in the readme work for me on ubuntu
Does not work on wsl, crostini

Give me more details for help

Edit:
I close the issue (1 month ago)
